//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inkybot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inkybot.Resources.RuneDictionary", typeof(RuneDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loc.
        /// </summary>
        internal static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agi.
        /// </summary>
        internal static string agility {
            get {
                return ResourceManager.GetString("agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air dam.
        /// </summary>
        internal static string air_damage {
            get {
                return ResourceManager.GetString("air_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air res.
        /// </summary>
        internal static string air_resistance {
            get {
                return ResourceManager.GetString("air_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Steal.
        /// </summary>
        internal static string air_steal {
            get {
                return ResourceManager.GetString("air_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ap ga.
        /// </summary>
        internal static string ap {
            get {
                return ResourceManager.GetString("ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ap res.
        /// </summary>
        internal static string ap_parry {
            get {
                return ResourceManager.GetString("ap_parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ap red.
        /// </summary>
        internal static string ap_reduction {
            get {
                return ResourceManager.GetString("ap_reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cha.
        /// </summary>
        internal static string chance {
            get {
                return ResourceManager.GetString("chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crit.
        /// </summary>
        internal static string critical {
            get {
                return ResourceManager.GetString("critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cri dam.
        /// </summary>
        internal static string critical_damage {
            get {
                return ResourceManager.GetString("critical_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cri res.
        /// </summary>
        internal static string critical_resistance {
            get {
                return ResourceManager.GetString("critical_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dam.
        /// </summary>
        internal static string damage {
            get {
                return ResourceManager.GetString("damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dod.
        /// </summary>
        internal static string dodge {
            get {
                return ResourceManager.GetString("dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earth dam.
        /// </summary>
        internal static string earth_damage {
            get {
                return ResourceManager.GetString("earth_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earth res.
        /// </summary>
        internal static string earth_resistance {
            get {
                return ResourceManager.GetString("earth_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Steal.
        /// </summary>
        internal static string earth_steal {
            get {
                return ResourceManager.GetString("earth_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire dam.
        /// </summary>
        internal static string fire_damage {
            get {
                return ResourceManager.GetString("fire_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire res.
        /// </summary>
        internal static string fire_resistance {
            get {
                return ResourceManager.GetString("fire_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Steal.
        /// </summary>
        internal static string fire_steal {
            get {
                return ResourceManager.GetString("fire_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hea.
        /// </summary>
        internal static string heals {
            get {
                return ResourceManager.GetString("heals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Restored.
        /// </summary>
        internal static string hp_restored {
            get {
                return ResourceManager.GetString("hp_restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hunting.
        /// </summary>
        internal static string hunting_weapon {
            get {
                return ResourceManager.GetString("hunting_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ini.
        /// </summary>
        internal static string initiative {
            get {
                return ResourceManager.GetString("initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int.
        /// </summary>
        internal static string intelligence {
            get {
                return ResourceManager.GetString("intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me dam per.
        /// </summary>
        internal static string melee_damage {
            get {
                return ResourceManager.GetString("melee_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me res per.
        /// </summary>
        internal static string melee_resistance {
            get {
                return ResourceManager.GetString("melee_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp ga.
        /// </summary>
        internal static string mp {
            get {
                return ResourceManager.GetString("mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp res.
        /// </summary>
        internal static string mp_parry {
            get {
                return ResourceManager.GetString("mp_parry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp red.
        /// </summary>
        internal static string mp_reduction {
            get {
                return ResourceManager.GetString("mp_reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neutral dam.
        /// </summary>
        internal static string neutral_damage {
            get {
                return ResourceManager.GetString("neutral_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neutral res.
        /// </summary>
        internal static string neutral_resistance {
            get {
                return ResourceManager.GetString("neutral_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral Steal.
        /// </summary>
        internal static string neutral_steal {
            get {
                return ResourceManager.GetString("neutral_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to air res per.
        /// </summary>
        internal static string per_air_resistance {
            get {
                return ResourceManager.GetString("per_air_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earth res per.
        /// </summary>
        internal static string per_earth_resistance {
            get {
                return ResourceManager.GetString("per_earth_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire res per.
        /// </summary>
        internal static string per_fire_resistance {
            get {
                return ResourceManager.GetString("per_fire_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neutral res per.
        /// </summary>
        internal static string per_neutral_resistance {
            get {
                return ResourceManager.GetString("per_neutral_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water res per.
        /// </summary>
        internal static string per_water_resistance {
            get {
                return ResourceManager.GetString("per_water_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pod.
        /// </summary>
        internal static string pods {
            get {
                return ResourceManager.GetString("pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power.
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tra per.
        /// </summary>
        internal static string power_traps {
            get {
                return ResourceManager.GetString("power_traps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prospe.
        /// </summary>
        internal static string prospecting {
            get {
                return ResourceManager.GetString("prospecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psh dam.
        /// </summary>
        internal static string pushback_damage {
            get {
                return ResourceManager.GetString("pushback_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psh res.
        /// </summary>
        internal static string pushback_resistance {
            get {
                return ResourceManager.GetString("pushback_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range.
        /// </summary>
        internal static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ra dam per.
        /// </summary>
        internal static string ranged_damage {
            get {
                return ResourceManager.GetString("ranged_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ra res per.
        /// </summary>
        internal static string ranged_resistance {
            get {
                return ResourceManager.GetString("ranged_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spe dam per.
        /// </summary>
        internal static string spell_damage {
            get {
                return ResourceManager.GetString("spell_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stre.
        /// </summary>
        internal static string strength {
            get {
                return ResourceManager.GetString("strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summo.
        /// </summary>
        internal static string summons {
            get {
                return ResourceManager.GetString("summons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tra.
        /// </summary>
        internal static string trap_damage {
            get {
                return ResourceManager.GetString("trap_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vit.
        /// </summary>
        internal static string vitality {
            get {
                return ResourceManager.GetString("vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water dam.
        /// </summary>
        internal static string water_damage {
            get {
                return ResourceManager.GetString("water_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water res.
        /// </summary>
        internal static string water_resistance {
            get {
                return ResourceManager.GetString("water_resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Steal.
        /// </summary>
        internal static string water_steal {
            get {
                return ResourceManager.GetString("water_steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we dam per.
        /// </summary>
        internal static string weapon_damage {
            get {
                return ResourceManager.GetString("weapon_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wis.
        /// </summary>
        internal static string wisdom {
            get {
                return ResourceManager.GetString("wisdom", resourceCulture);
            }
        }
    }
}
